### ISSUE TITLE
Error during the submission

### ISSUE THREAD

**Issue by vrsb2006** [seungjaeryanlee/osim-rl-helper#4]
When I run the following command

`./run.py RandomAgent -s`

I get the following error

> ServerErrorPrint Expecting value: line 1 column 1 (char 0) 400
> Expecting value: line 1 column 1 (char 0)

Any clues??

**Comment by seungjaeryanlee** [comment]
Hello. I just tested the command in my computer and verified it worked. Do you mind checking if your version is up to date with `git pull`?

Sorry for the inconvenience!

**Comment by vrsb2006** [comment]
I just checked with git pull. It is up to date. 

One change though I made in **helper/baselines/__init__.py**.  I commented the last two lines, i.e.

```
# from .keras import *
# from .tensorforce import *
```

because it was giving me error related to rl.agents and tensorforce. After commenting, it was running and I was visually able to see the skeleton output. But above mentioned arise during the submission mode. 

On a separate note, Can you tell me other dependencies (apart from keras, tensorflow) that are needed to run this project ?

EDIT:

I installed keras-rl and tensorforce. So, **TensorforcePPOAgent** and **KerasDDPGAgent** is working now :)
But the problem with submission still persists.

**Comment by seungjaeryanlee** [comment]
I'll add the dependencies this weekend, but if the agent runs locally, I doubt it is due to missing dependencies. I am leaning towards temporary server or communication issue. What are the status and messages of your submission on the server? You can [check it here](https://www.crowdai.org/challenges/nips-2018-ai-for-prosthetics-challenge/submissions?current_round_id=47&my_submissions=on).

Thank you for your patience.
